[package]
name = "panoply"
version = "0.1.0"
edition = "2021"

# [workspace]
# exclude = [
#   "benches",
#   "crates/bevy_ecs_compile_fail_tests",
#   "crates/bevy_macros_compile_fail_tests",
#   "crates/bevy_reflect_compile_fail_tests",
# ]
# members = [
#   "crates/*",
#   "examples/mobile",
#   "tools/ci",
#   "tools/build-templated-pages",
#   "tools/build-wasm-example",
#   "tools/example-showcase",
#   "errors",
# ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.11.0", features = ["dynamic_linking"] }
bevy_egui = "0.21.0"
cargo-wgsl = "0.0.14"
directories = "5.0.1"
egui = "0.22.0"
futures-lite = "1.13.0"
lazy_static = "1.4.0"
lru = "0.11.0"
quick-xml = "0.30.0"
regex = "1.9.3"
rmp-serde = "1.1.2"
serde = "1.0.171"
serde_bytes = "0.11.12"
serde_derive = "1.0.171"
serde_json = "1.0.103"
serde_repr = "0.1.16"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3
