[package]
name = "bevy_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.11.0", features = ["dynamic_linking"] }
bevy_egui = "0.21.0"
directories = "5.0.1"
egui = "0.22.0"
lru = "0.11.0"
serde = "1.0.171"
serde_arrays = "0.1.0"
serde_derive = "1.0.171"
serde_json = "1.0.103"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3
